service: serverless-geoip

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 120
  region: us-east-1

package:
  exclude:
    - .gitignore
    - CODE_OF_CONDUCT.md
    - dist/**
    - LICENSE.md
    - README.md
    - yarn.lock
    - package.json
    - package-lock.json

functions:
  lookup:
    handler: src/lookup.run
    timeout: 120
    memorySize: 128

  http:
    handler: src/http.run
    memorySize: 128
    timeout: 120
    events:
      - http:
          method: GET
          path: /lookup
